language: node_js

cache: npm

stages:
  - lint
  - build

jobs:
  include:
    - stage: lint
      node_js:
        - "11"
      script: npm run lint

    - stage: build
      node_js:
        - "11"
      script: npm run build
